cloud_providers:
  gcp:
    disabled: false
    project_id: my-project
    network: default
  aws:
    disabled: false
    region: us-east1
    firewall_policy: my-firewall-policy2
    capacity: 200
    rule_group_priority: 100
rule_name_prefix: crowdsec
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
api_url: http://crowdsec:8080
api_key: 12345
